### PR TITLE
Add my talk about the CakePHP Fixture Factories

### PR DESCRIPTION
**Pull request by pabloelcolombiano**

### CODE REVIEW

**Comment by woodworker** [comment]
hi [pabloelcolombiano](https://github.com/pabloelcolombiano) 

i just saw your PR, never got a notification or anything, strage
do you maybe want to reenter your talk for june?

**Comment by pabloelcolombiano** [comment]
Hi there!
Yes, with pleasure. Should I submit a new PR?

**Comment by woodworker** [comment]
yes, this would be awesome

**Comment by pabloelcolombiano** [comment]
The presentation should interest any TDD interested or confirmed developer. I can do any format, let me just know how long.

**Comment by pabloelcolombiano** [comment]
> yes, this would be awesome

Will do

**Comment by pabloelcolombiano** [comment]
@woodworker there you are!

**Pull request merged**
