### PR TITLE
Submit my talk about self-contained system

### PR DESCRIPTION
**Pull request by SebTM**
I'm happy to get to know you all and talk with you about my interpretation of Self-contained Systems with a practical example (based on Lumen).

### CODE REVIEW

**Comment by chluehr** [comment]
Sorry, did not see your pull request prior to manually adding a second proposal we received - put yours on the 3rd spot now - hope that is ok! I am very much looking forward to hear your talk!

**Comment by chluehr** [comment]
oh - btw - talk is in english right? I would change the subtitle to english then if thats ok?

**Comment by SebTM** [comment]
It's currently prepared for german but if this is a problem due to some participants which speak english only, I will try to prepare it/me for holding it in english :)

**Comment by chluehr** [comment]
Tatsaechlich haben wir praktisch immer alle Talks in Englisch, da ca 30-60% der Teilnehmer nur Englisch sprechen - sprich, Talk auf Englisch waere schon gut =) 
Die Berliner PHP UG ist aber immer sehr nice - und es muss auch kein top-englisch sein; Ist aber super zum Ueben fuer internationale Veranstaltungen!

**Comment by SebTM** [comment]
Alles klar, kein Problem - dann bereite ich das ensprechend vor 👍 
Danke für das ändern des Titels :) Freue mich auf die Veranstaltung!

**Pull request merged**
