### PR TITLE
Nette\Tester talk proposal

### PR DESCRIPTION
**Pull request by jkuchar**
Hi, this is my proposal for a talk. I assume that audience know how unit tests work (in general).

It will be short: ~ 7 mins

I'm from the same group as @TomasVotruba and @OndraM.

### CODE REVIEW

**Comment by TomasVotruba** [comment]
@chluehr Honza is last member of our team. I was not sure if he has time, but we spoke and he has.
Let me know if we can fit in the schedule.

**Comment by jkuchar** [comment]
@chluehr I need to buy train ticket till midnight, please could you accept or reject my proposal? Thanks!

**Comment by jkuchar** [comment]
I will propose my talk again at some later meetup. Thanks for organising bePHPug and see you there next time! :)

**Comment by TomasVotruba** [comment]
@jkuchar I'd keep this open. It's never too late :)

**Pull request closed without merging**
