### PR TITLE
Selenium & PHPUnit & Steward task proposal for April meetup

### PR DESCRIPTION
**Pull request by OndraM**
Hi, here is my proposal for April meetup. Talk level is ~intermediate.

BTW I've spoken with some other guys and there should be some proposals for the April meetup from them as well (@jkuchar and @JanTvrdik i think), so I suggest to wait for them and then made a selection? Or are you eventually able to accept more than 3 talks for the meetup :)?

Thanks :)

### CODE REVIEW

**Comment by chluehr** [comment]
Hi & thank you very much for your proposal!
Actually, just about half an hour ago i agreed to take in a 3rd talk (but havent had the time to update the site) by Frank Sons of the Hamburg UG who is in town next week....
More than 3 talks usually is too long for scheduled time-frame ... do you think you (and your colleagues?) could do your talks in may, instead?

**Comment by OndraM** [comment]
Oh, thats unfortunate :-(. Well I happen to have some time next week so I was considering to join @TomasVotruba on his trip from Prague. However because of my time schedule I cannot currently tell if will be able to attend in following months :-/.

**Comment by TomasVotruba** [comment]
We are actually planning a trip from Prague with 12 hours in train in total. That's the main reason we agreed in group on same date to take 2 days off or home office in work.

Also, I could shorten mine to 10 minutes. I'm getting better and better in that.

I think @ondraM has interesting topic to talk about, proven on few conferences.

I'd appreciate if you consider our bit crazy and bold situation. 

Still, I understand you'd like to organize event properly and we are only guests, so I'll respect your preferences.

**Comment by chluehr** [comment]
I understand. Well, if the other speakers keep their time (or use less) and if people are willing to stay a bit longer, we might be able to fit in another ±20 minutes - but i would be very careless to ensure you this is going to work... So if you have not planned anything else the evening and want to take the risk, feel free to show up and we will see if people would like to stay/see one or two additional short talks. I do not want to disappoint you guys if it just won't fit in ...
Me personally would very much like to see your talks!

Sorry for the late reply, too!

**Comment by chluehr** [comment]
OMG - so sorry; I did not get that you, Tomas, actually had you presentation already listed! (so i thought we were talking about 5 talks - not 4).

so 4 talks should work, if we keep them concise - i'll add @OndraM's right away =)

Sorry for my misunderstanding!

**Comment by TomasVotruba** [comment]
Thanks for the reply :+1: 

We can always add more ;-) , but it looks like other guys didn't send any PRs. So 4 in total it is now.

I'll keep it short, thank you for helping in us. I'm happy :smiley:

**Pull request closed without merging**
