### PR TITLE
Submit "Design Patterns: Abstract Factory" talk proposal

### PR DESCRIPTION
**Pull request by tim-bezhashvyly**

### CODE REVIEW

**Comment by rmehner** [comment]
Looks like we're going to have a design pattern heavy meetup in March, you might wanna look into #92 by @anthonybieber :)

**Comment by tim-bezhashvyly** [comment]
Not sue how design patterns (and anti-patterns) can be covered in 25 minutes but it makes it even more interesting.

**Comment by till** [comment]
@tim-bezhashvyly please let us know how much time you anticipate and we'll discuss!

**Comment by tim-bezhashvyly** [comment]
No I meant the other speaker. However we already got in touch with him and agreed that he will just skip abstract factories.

**Pull request merged**
