### PR TITLE
Add talk about PHPUnit

### PR DESCRIPTION
**Pull request by keradus**
**Warning** it would take longer than 25 mins, probably ~45

going a bit deeper to PHPUnit to see how properly use it to squeeze all goods out of it

### CODE REVIEW

**Comment by keradus** [comment]
huh, funny, after my git-clone new topic already arrived ;)

well, maybe next time...

**Comment by chluehr** [comment]
Hi,
so sorry! It is kind of hard to keep track who/when/where a new
talk is submitted - in this case, Erik (3rd slot) proposed the talk
via meetup.com in the afternoon and i've added it 7:30pm, though.

Would really love to see your talk on one of our next Meetups!

**Comment by keradus** [comment]
> Warning it would take longer than 25 mins, probably ~45

please comment, so I would know is it a blocker or not

**Comment by chluehr** [comment]
Actually, we really strive to have individual talks in under 30Min b/c sometimes, Q&A is on top. If  there is only two or just one talk scheduled for a Meetup, then a longer talk would be possible - this is usually only know a few days ahead of the actual Meetup, though.

I don't know if my previous message or me closing the PR was misleading - we (sadly) can not take your talk for the April Meetup. The (next) May date is a public holiday, so we are going to skip this meetup, too. Next scheduled meetup with free slots would be June, then ...

**Comment by keradus** [comment]
I fully got it for April, Simply, I was still wondering would it make sense to raise my papers for next meetup, or too long talk is disqualification for it.
So now, I know it's kinda doesn't make sense to propose it again.

BTW, if 1st Tue of May is off, why not go with 2nd one ?

**Pull request closed without merging**
