### PR TITLE
Propose "Design Patterns: Builder, Value Objects" presentation

### PR DESCRIPTION
**Pull request by tim-bezhashvyly**

### CODE REVIEW

**Comment by tim-bezhashvyly** [comment]
Thanks for merging.

Not sure if it is on purpose but the website is still showing the page from the last month.

**Comment by JeroenDeDauw** [comment]
I've just spend 5 mins trying to find out what the date of the next event is and am still in the dark...

**Comment by woodworker** [comment]
@JeroenDeDauw the date is in the header of the file and i published the september now

AND it's always the first tuesday in the month

**Comment by JeroenDeDauw** [comment]
Thanks

**Pull request merged**
